export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RECEIVE = 'LOGIN_RECEIVE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_TOKEN_RECEIVE = 'LOGIN_TOKEN_RECEIVE';
export const LOGIN_TOKEN_REQUEST = 'LOGIN_TOKEN_REQUEST';
export const LOGIN_TOKEN_FAILED = 'LOGIN_TOKEN_FAILED';
export const ERROR = 'ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_RECEIVE = 'LOGOUT_RECEIVE';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
export const LOADING = 'LOADING';

export const POSTS_REQUEST = 'POSTS_REQUEST';
export const POSTS_RECEIVE = 'POSTS_RECEIVE';
export const POSTS_FAILED = 'POSTS_FAILED';

export const POST_REQUEST = 'POST_REQUEST';
export const POST_RECEIVE = 'POST_RECEIVE';
export const POST_FAILED = 'POST_FAILED';
